version: '3.8'
services:
  backend:
    stdin_open: true
    tty: true
    container_name: softkeyz
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8888:8888'
    command: npm run dev
  # client:
  #   stdin_open: true
  #   tty: true
  #   container_name: softkeyz:client
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./client:/app/client
  #     - /app/client/node_modules
  #     - /app/client/.next
