version: '3.8'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisDB:/data

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongoDB:/data

  postgresql:
    image: 'bitnami/postgresql:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: my_user
      POSTGRESQL_PASSWORD: password123
      POSTGRESQL_DATABASE: softkeyz_db
    volumes:
      - progresDB:/data

  nginx:
    depends_on:
      - api
      - admin
      - client
    build:
      dockerfile: Dockerfile
      context: ./nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx:/app/nginx
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: 'postgresql://my_user:$password123@postgresql:5432/softkeyz_db?schema=public'
    depends_on:
      - postgresql
      - redis
      - mongo
    ports:
      - '8888:8888'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - /app/client/.next
    ports:
      - '3000:3000'

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    volumes:
      - ./admin:/app/admin
      - /app/admin/node_modules
    ports:
      - '5173:5173'

volumes:
  progresDB:
  redisDB:
  mongoDB:
