version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y docker-compose

      - run:
          name: Build and run containers
          command: |
            docker-compose up -d

      - run:
          name: Run tests
          command: |
            docker-compose exec api npm run test
