FROM node:alpine as build

WORKDIR /app/admin

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build
# EXPOSE 5173

FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/admin/dist/ /usr/share/nginx/html
# Expose cổng 80
EXPOSE 80
